# Generated by Django 3.1.4 on 2020-12-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patients_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
