# Generated by Django 3.1.4 on 2021-01-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doctor_physician'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profession',
            field=models.CharField(choices=[('GH', 'General_Health'), ('CD', 'Cardiology'), ('D', 'Dental'), ('R', 'Research')], max_length=3, null=True),
        ),
    ]
