# Generated by Django 3.1.4 on 2020-12-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201227_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_profile',
            name='image',
            field=models.ImageField(default='patient_pics/default.png', upload_to='patient_pics'),
        ),
    ]
