# Generated by Django 3.1.4 on 2021-01-13 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_doctor_profession'),
        ('main', '0003_auto_20201227_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='patient_pics/default.png', upload_to='patient_pics')),
                ('doctor_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
            ],
        ),
    ]
