# Generated by Django 3.1.4 on 2021-01-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210114_0159'),
        ('main', '0005_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugallergies', models.TextField(default='None', max_length=300, null=True)),
                ('all_illness', models.TextField(default='None', max_length=400, null=True)),
                ('all_operations', models.TextField(default='None', max_length=400, null=True)),
                ('current_medication', models.TextField(default='None', max_length=400, null=True)),
                ('patient_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
